# Generated by Django 3.2 on 2023-01-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='postvideo',
            options={'verbose_name_plural': 'Videos'},
        ),
    ]
