# Generated by Django 3.2 on 2023-01-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230119_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={},
        ),
    ]
