# Generated by Django 3.2 on 2023-01-20 01:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postcomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='postvideo',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Videos'},
        ),
        migrations.AddField(
            model_name='postimage',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
