# Generated by Django 3.2 on 2023-01-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230120_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvideo',
            name='hls_url',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
