# Generated by Django 4.2 on 2024-05-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_postvideo_hls_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
