# Generated by Django 3.2 on 2023-01-07 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('slug', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=profiles.models.profile_image_path)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=profiles.models.cover_image_path)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, help_text='male , female or others', max_length=20, null=True)),
                ('phone_code', models.CharField(help_text='E.g. 880 excluding + ( i.e. 880 not +880 )', max_length=10)),
                ('mobile_number', models.CharField(help_text='+8801XXXXXXXXX (Must match with User table)', max_length=25)),
                ('password', models.CharField(help_text='(Must match with User table)', max_length=50)),
                ('streaming_title', models.CharField(blank=True, max_length=200, null=True)),
                ('diamonds', models.IntegerField(default=0, help_text='Present diamonds')),
                ('gift_diamonds', models.IntegerField(default=0, help_text='Total diamonds')),
                ('loves', models.IntegerField(default=0)),
                ('registered_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('blocks', models.ManyToManyField(blank=True, related_name='streaming_blocks', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='streaming_followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
