# Generated by Django 3.2 on 2023-07-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='be_agent_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='be_host_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='be_moderator_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='be_reseller_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='converted_coins',
            field=models.BigIntegerField(default=0, help_text='Converted coins'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_allow_video_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_reseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='login_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='outgoing_diamonds',
            field=models.BigIntegerField(default=0, help_text='Outgoing diamonds'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diamonds',
            field=models.BigIntegerField(default=0, help_text='Present diamonds'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, help_text='(Must match with User table)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_code',
            field=models.CharField(blank=True, help_text='E.g. 880 excluding + ( i.e. 880 not +880 )', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
