# Generated by Django 3.2 on 2023-09-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20230706_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gift_diamonds',
            field=models.BigIntegerField(default=0, help_text='Total diamonds'),
        ),
    ]
