# Generated by Django 4.2 on 2023-11-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_gift_diamonds'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_password',
            field=models.CharField(blank=True, help_text='Password must contain at least 8 characters.', max_length=50, null=True),
        ),
    ]
