# Generated by Django 4.2 on 2024-04-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_reset_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_notification_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
