# Generated by Django 4.2 on 2024-06-15 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_last_notification_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='converted_coins',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gift_diamonds',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='loves',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reset_password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
