# Generated by Django 4.2 on 2023-09-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(default=0)),
                ('is_pk', models.BooleanField(default=False)),
                ('group_caller_ids', models.CharField(default='[]', max_length=50)),
            ],
        ),
    ]
