# Generated by Django 4.2 on 2023-11-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livekit_stuffs', '0002_liveroom_created_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveRoom',
        ),
    ]
