# Generated by Django 4.2 on 2024-03-27 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livekit_stuffs', '0003_delete_liveroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveGroupRoomConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_audio_lock', models.BooleanField(default=True)),
                ('is_audio_gp_room2_lock', models.BooleanField(default=True)),
                ('is_audio_gp_room3_lock', models.BooleanField(default=True)),
                ('is_audio_gp_room4_lock', models.BooleanField(default=True)),
                ('is_audio_gp_room5_lock', models.BooleanField(default=True)),
                ('is_audio_gp_room6_lock', models.BooleanField(default=True)),
                ('is_audio_gp_room7_lock', models.BooleanField(default=True)),
                ('is_audio_gp_room8_lock', models.BooleanField(default=True)),
                ('is_audio_gp_room9_lock', models.BooleanField(default=True)),
                ('is_audio_gp_call_paid', models.BooleanField(default=False)),
                ('audio_gp_call_cost_in_minute', models.IntegerField(default=100)),
                ('is_video_normal', models.BooleanField(default=True)),
                ('is_video_lock', models.BooleanField(default=False)),
                ('is_video_gp_room2_lock', models.BooleanField(default=True)),
                ('is_video_gp_room3_lock', models.BooleanField(default=True)),
                ('is_video_gp_room4_lock', models.BooleanField(default=True)),
                ('is_video_gp_room5_lock', models.BooleanField(default=True)),
                ('is_video_gp_room6_lock', models.BooleanField(default=True)),
                ('is_video_gp_room7_lock', models.BooleanField(default=True)),
                ('is_video_gp_room8_lock', models.BooleanField(default=True)),
                ('is_video_gp_call_paid', models.BooleanField(default=False)),
                ('video_gp_call_cost_in_minute', models.IntegerField(default=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Live Group Room Configuration',
            },
        ),
    ]
