# Generated by Django 4.2 on 2024-03-28 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livekit_stuffs', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livegrouproomconfig',
            old_name='is_video_normal',
            new_name='is_video_request',
        ),
    ]
