# Generated by Django 4.2 on 2024-09-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livekit_stuffs', '0005_rename_is_video_normal_livegrouproomconfig_is_video_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=100)),
                ('is_pk', models.BooleanField(default=False)),
                ('is_video', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('allow_send', models.BooleanField(default=True)),
                ('cm_flt_nm', models.CharField(default='Hudson', max_length=50)),
                ('group_caller_ids', models.TextField(default='[]')),
                ('reacts', models.BigIntegerField(default=0)),
                ('viewers_count', models.IntegerField(default=0)),
                ('locked_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
