# Generated by Django 4.2 on 2025-08-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livekit_stuffs', '0006_liveroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='livegrouproomconfig',
            name='is_video_gp_room9_lock',
            field=models.BooleanField(default=True),
        ),
    ]
