# Generated by Django 3.2 on 2023-01-06 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('device_name', models.CharField(max_length=200)),
                ('device_id', models.CharField(max_length=200, unique=True)),
                ('blocked', models.BooleanField(default=False)),
                ('entry_datetime', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'User Devices Information',
                'ordering': ['-entry_datetime'],
            },
        ),
        migrations.CreateModel(
            name='UserDeviceBlocked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('device_name', models.CharField(max_length=200)),
                ('device_id', models.CharField(max_length=200, unique=True)),
                ('blocked_datetime', models.DateTimeField(auto_now_add=True)),
                ('device_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.userdeviceinfo')),
            ],
            options={
                'verbose_name_plural': 'User Devices Blocked List',
                'ordering': ['-blocked_datetime'],
            },
        ),
    ]
