# Generated by Django 3.2 on 2023-02-05 05:55

import balance.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('slug', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('logo', models.ImageField(upload_to=balance.models.payment_method_logo_path)),
                ('percent_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance.paymentmethod')),
            ],
        ),
    ]
