# Generated by Django 3.2 on 2023-02-05 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balance', '0002_paymentmethod_paymentmethodaccounttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('received_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('receiver_number', models.CharField(max_length=50)),
                ('feedback', models.CharField(blank=True, max_length=350, null=True)),
                ('is_pending', models.BooleanField(default=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_declined', models.BooleanField(default=False)),
                ('requested_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='balance.paymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Withdraw Requests',
                'ordering': ['-id'],
            },
        ),
    ]
