# Generated by Django 3.2 on 2023-02-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_withdrawrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='diamonds',
            field=models.IntegerField(default=0),
        ),
    ]
