# Generated by Django 3.2 on 2023-02-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0005_withdrawrequest_withdraw_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='account_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='payment_method_name',
            field=models.CharField(default='bKash', max_length=20),
            preserve_default=False,
        ),
    ]
