# Generated by Django 3.2 on 2023-02-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0006_auto_20230205_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='percent_charge',
            new_name='charge',
        ),
    ]
