# Generated by Django 3.2 on 2023-08-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0007_rename_percent_charge_paymentmethod_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearContributionRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_contribution_ranking_zero', models.CharField(blank=True, help_text="Type 'Zero' and Save it (It's Case Sensitive)", max_length=4, null=True)),
                ('last_contribution_ranking_clear_datetime', models.DateTimeField(blank=True, null=True)),
                ('upcoming_contribution_ranking_clear_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clear Contribution Rankings',
            },
        ),
    ]
