# Generated by Django 3.2 on 2023-09-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0008_clearcontributionranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='diamonds',
            field=models.BigIntegerField(default=0),
        ),
    ]
