# Generated by Django 3.2 on 2023-01-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='E.g. +8801XXXXXXXXX ( Must include country code with + i.e. +880 )', max_length=14, unique=True),
        ),
    ]
