# Generated by Django 3.2 on 2023-07-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='E.g. +8801XXXXXXXXX or Email', max_length=250, unique=True, verbose_name='Phone / Email'),
        ),
    ]
