# Generated by Django 4.2 on 2024-06-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatvat',
            name='chat_diamonds',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='chatvat',
            name='vat_diamonds',
            field=models.IntegerField(default=50),
        ),
    ]
