# Generated by Django 4.2 on 2024-06-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chatvat_chat_diamonds_alter_chatvat_vat_diamonds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatvat',
            old_name='chat_diamonds',
            new_name='cost_diamonds',
        ),
    ]
