# Generated by Django 4.2 on 2024-06-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_rename_chat_diamonds_chatvat_cost_diamonds'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatVat',
            new_name='ChatCost',
        ),
        migrations.AlterModelOptions(
            name='chatcost',
            options={'verbose_name_plural': 'Chat Cost Diamonds'},
        ),
    ]
