# Generated by Django 3.2 on 2023-02-05 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferBonusAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamonds', models.IntegerField(default=30)),
            ],
            options={
                'verbose_name_plural': "Diamonds of Refer Bonus (Don't add multiple rule)",
            },
        ),
        migrations.CreateModel(
            name='ReferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refered_uid', models.IntegerField(default=0)),
                ('referer_uid', models.IntegerField(default=0)),
                ('device_name', models.CharField(max_length=200)),
                ('device_id', models.CharField(max_length=200, unique=True)),
                ('diamonds', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('device_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.userdeviceinfo')),
            ],
            options={
                'verbose_name_plural': 'Refer Histories',
                'ordering': ['-datetime'],
            },
        ),
    ]
