# Generated by Django 3.2 on 2023-04-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FortuneWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog', models.BigIntegerField(default=0)),
                ('dog_times', models.IntegerField(default=10)),
                ('cat', models.BigIntegerField(default=0)),
                ('cat_times', models.IntegerField(default=5)),
                ('mouse', models.BigIntegerField(default=0)),
                ('mouse_times', models.IntegerField(default=5)),
                ('bear', models.BigIntegerField(default=0)),
                ('bear_times', models.IntegerField(default=15)),
                ('panda', models.BigIntegerField(default=0)),
                ('panda_times', models.IntegerField(default=5)),
                ('tiger', models.BigIntegerField(default=0)),
                ('tiger_times', models.IntegerField(default=25)),
                ('lion', models.BigIntegerField(default=0)),
                ('lion_times', models.IntegerField(default=45)),
                ('cow', models.BigIntegerField(default=0)),
                ('cow_times', models.IntegerField(default=5)),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fortune Wheel',
            },
        ),
    ]
