# Generated by Django 3.2 on 2023-04-19 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortunewheel',
            name='bear_choosers',
            field=models.ManyToManyField(blank=True, related_name='bear_choosers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fortunewheel',
            name='cat_choosers',
            field=models.ManyToManyField(blank=True, related_name='cat_choosers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fortunewheel',
            name='cow_choosers',
            field=models.ManyToManyField(blank=True, related_name='cow_choosers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fortunewheel',
            name='dog_choosers',
            field=models.ManyToManyField(blank=True, related_name='dog_choosers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fortunewheel',
            name='lion_choosers',
            field=models.ManyToManyField(blank=True, related_name='lion_choosers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fortunewheel',
            name='mouse_choosers',
            field=models.ManyToManyField(blank=True, related_name='mouse_choosers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fortunewheel',
            name='panda_choosers',
            field=models.ManyToManyField(blank=True, related_name='panda_choosers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fortunewheel',
            name='tiger_choosers',
            field=models.ManyToManyField(blank=True, related_name='tiger_choosers', to=settings.AUTH_USER_MODEL),
        ),
    ]
