# Generated by Django 3.2 on 2023-04-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20230419_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fortunewheel',
            old_name='lion',
            new_name='lion_face',
        ),
        migrations.RenameField(
            model_name='fortunewheel',
            old_name='lion_choosers',
            new_name='lion_face_choosers',
        ),
        migrations.RenameField(
            model_name='fortunewheel',
            old_name='lion_times',
            new_name='lion_face_times',
        ),
        migrations.RenameField(
            model_name='fortunewheel',
            old_name='panda',
            new_name='panda_face',
        ),
        migrations.RenameField(
            model_name='fortunewheel',
            old_name='panda_choosers',
            new_name='panda_face_choosers',
        ),
        migrations.RenameField(
            model_name='fortunewheel',
            old_name='panda_times',
            new_name='panda_face_times',
        ),
        migrations.AddField(
            model_name='fortunewheel',
            name='winner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
