# Generated by Django 3.2 on 2023-04-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20230419_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortunewheel',
            name='dog_played_diamonds',
            field=models.TextField(default='{}'),
        ),
    ]
