# Generated by Django 4.2 on 2023-10-25 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0005_auto_20230421_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fortunewheel',
            old_name='banana_played_diamonds',
            new_name='winning_diamonds',
        ),
        migrations.RemoveField(
            model_name='fortunewheel',
            name='banana',
        ),
        migrations.RemoveField(
            model_name='fortunewheel',
            name='banana_choosers',
        ),
        migrations.RemoveField(
            model_name='fortunewheel',
            name='banana_times',
        ),
        migrations.RemoveField(
            model_name='fortunewheel',
            name='melon',
        ),
        migrations.RemoveField(
            model_name='fortunewheel',
            name='melon_choosers',
        ),
        migrations.RemoveField(
            model_name='fortunewheel',
            name='melon_played_diamonds',
        ),
        migrations.RemoveField(
            model_name='fortunewheel',
            name='melon_times',
        ),
        migrations.RemoveField(
            model_name='fortunewheel',
            name='winner',
        ),
        migrations.AddField(
            model_name='fortunewheel',
            name='played_diamonds',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='fortunewheel',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fortunewheel',
            name='top_played_diamonds',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='fortunewheel',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fortunewheel',
            name='winner_history',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fortunewheel',
            name='winner_index',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='fortunewheel',
            name='apple_times',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='fortunewheel',
            name='coconut_times',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='fortunewheel',
            name='cucumber_times',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='fortunewheel',
            name='mango_times',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='fortunewheel',
            name='pineapple_times',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='fortunewheel',
            name='strawberry_times',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='fortunewheel',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FortuneWheelPeriodicTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.IntegerField(default=0)),
                ('repeats', models.IntegerField(default=0)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fortune_wheel_tracker', to='games.fortunewheel')),
            ],
        ),
    ]
