# Generated by Django 4.2 on 2024-10-02 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=200)),
                ('key', models.CharField(blank=True, max_length=200, null=True)),
                ('sender_id', models.PositiveIntegerField(default=0)),
                ('receiver_id', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LastChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=200)),
                ('key', models.CharField(blank=True, max_length=200, null=True)),
                ('user_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('sender_id', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(max_length=20)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('profile_image', models.CharField(blank=True, max_length=250, null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(default=0)),
                ('blocks', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
