# Generated by Django 3.2 on 2023-01-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeleteAndUsernameChangeDiamonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_diamonds', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Account Delete and Username Change Diamonds',
            },
        ),
        migrations.CreateModel(
            name='FlyingMessageAndBoostDiamonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_diamonds', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Flying Message and Boost Diamonds',
            },
        ),
        migrations.CreateModel(
            name='GiftSendVatDiamonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_diamonds', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Gift Send Vats Diamonds',
            },
        ),
        migrations.CreateModel(
            name='RechargeDiamonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_diamonds', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Recharge Diamonds',
            },
        ),
        migrations.CreateModel(
            name='ReferBonusDiamonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_diamonds', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Refer Bonus Diamonds',
            },
        ),
        migrations.CreateModel(
            name='TotalDeviceBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_blocks', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Totoal Device Blocks',
            },
        ),
        migrations.CreateModel(
            name='TotalUsrsAndDiamonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField(default=0)),
                ('total_diamonds', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Total Users and Diamonds',
            },
        ),
        migrations.CreateModel(
            name='WithdrawDiamonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_diamonds', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Withdraw Diamonds',
            },
        ),
    ]
