# Generated by Django 3.2 on 2023-01-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdeleteandusernamechangediamonds',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flyingmessageandboostdiamonds',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giftsendvatdiamonds',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rechargediamonds',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referbonusdiamonds',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totaldeviceblocks',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalusrsanddiamonds',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawdiamonds',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
