# Generated by Django 3.2 on 2023-01-19 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20230111_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totaldeviceblocks',
            options={'verbose_name_plural': 'Total Device Blocks'},
        ),
    ]
