# Generated by Django 3.2 on 2023-04-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_totaldeviceblocks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesDiamonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested_diamonds', models.BigIntegerField(default=0)),
                ('recent_diamonds', models.BigIntegerField(default=0)),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Games Diamonds',
            },
        ),
    ]
