# Generated by Django 3.2 on 2023-07-06 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20230423_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcasterhistory',
            options={'ordering': ['-broadcasting_date'], 'verbose_name_plural': 'Broadcaster Histories'},
        ),
    ]
