# Generated by Django 3.2 on 2023-08-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_alter_broadcasterhistory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearBroadcasterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_clear_all_broadcasters_histories', models.CharField(blank=True, help_text="Type 'Zero' and Save it (It's Case Sensitive)", max_length=4, null=True)),
                ('last_clear_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Removing All Broadcaster Histories',
            },
        ),
    ]
