# Generated by Django 3.2 on 2023-08-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_clearbroadcasterhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftsendvatdiamonds',
            old_name='total_diamonds',
            new_name='gift_vat_diamonds',
        ),
        migrations.AddField(
            model_name='giftsendvatdiamonds',
            name='live_lock_vat_diamonds',
            field=models.IntegerField(default=0),
        ),
    ]
