# Generated by Django 4.2 on 2023-11-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_auto_20230811_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_number', models.IntegerField(default=0)),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'App Lock',
            },
        ),
    ]
