# Generated by Django 4.2 on 2024-06-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_applock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSendVatDiamonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_vat_diamonds', models.BigIntegerField(default=0)),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Chat Send Vats Diamonds',
            },
        ),
        migrations.AlterField(
            model_name='accountdeleteandusernamechangediamonds',
            name='total_diamonds',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='applock',
            name='build_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='broadcasterhistory',
            name='audio_broadcast_in_second',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='broadcasterhistory',
            name='video_broadcast_in_second',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flyingmessageandboostdiamonds',
            name='total_diamonds',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='giftsendvatdiamonds',
            name='gift_vat_diamonds',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='giftsendvatdiamonds',
            name='live_lock_vat_diamonds',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rechargediamonds',
            name='total_diamonds',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referbonusdiamonds',
            name='total_diamonds',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='totaldeviceblocks',
            name='total_blocks',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='totalusersanddiamonds',
            name='total_diamonds',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='totalusersanddiamonds',
            name='total_users',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='withdrawdiamonds',
            name='total_diamonds',
            field=models.BigIntegerField(default=0),
        ),
    ]
