# Generated by Django 3.2 on 2023-01-06 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimatedGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif', models.ImageField(upload_to=products.models.animated_gift_gif_path)),
                ('audio', models.FileField(blank=True, null=True, upload_to=products.models.animated_gift_audio_path)),
                ('diamonds', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['diamonds'],
            },
        ),
        migrations.CreateModel(
            name='DiamondPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamonds', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
            options={
                'ordering': ['diamonds'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('diamonds', models.IntegerField(default=0)),
                ('frame_gif', models.ImageField(upload_to=products.models.level_frame_gif_path)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='NormalGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_image', models.ImageField(upload_to=products.models.normal_gift_path)),
                ('diamonds', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['diamonds'],
            },
        ),
        migrations.CreateModel(
            name='StreamingJoiningGif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif', models.ImageField(upload_to=products.models.streaming_joining_gif_path)),
                ('diamonds', models.IntegerField(default=0)),
                ('days', models.IntegerField(default=0, verbose_name='Validity Days')),
            ],
            options={
                'ordering': ['diamonds'],
            },
        ),
        migrations.CreateModel(
            name='PurchasedStreamingJoiningGif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('purchased_datetime', models.DateTimeField()),
                ('expired_datetime', models.DateTimeField()),
                ('joining_gif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.streamingjoininggif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_datetime'],
            },
        ),
    ]
