# Generated by Django 3.2 on 2023-01-11 04:04

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animatedgift',
            name='vat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='normalgift',
            name='vat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='level',
            name='frame_gif',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.level_frame_gif_path),
        ),
    ]
