# Generated by Django 3.2 on 2023-02-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230111_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamonds', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
            options={
                'ordering': ['diamonds'],
            },
        ),
    ]
