# Generated by Django 3.2 on 2023-04-06 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_withdrawpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif', models.ImageField(upload_to=products.models.package_theme_gif_path)),
                ('diamonds', models.IntegerField(default=0)),
                ('days', models.IntegerField(default=0, verbose_name='Validity Days')),
            ],
            options={
                'ordering': ['diamonds'],
            },
        ),
        migrations.CreateModel(
            name='PurchasedPackageTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('purchased_datetime', models.DateTimeField()),
                ('expired_datetime', models.DateTimeField()),
                ('package_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.packagetheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_datetime'],
            },
        ),
    ]
