# Generated by Django 4.2 on 2023-10-25 13:19

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_packagetheme_purchasedpackagetheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif', models.ImageField(upload_to=products.models.vip_gif_path)),
                ('price', models.IntegerField(default=0, help_text='BDT')),
                ('days', models.IntegerField(default=0, verbose_name='Validity Days')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='VipPackageOrderingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Vip Package Ordering Info',
            },
        ),
        migrations.CreateModel(
            name='VVipPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif', models.ImageField(upload_to=products.models.vvip_gif_path)),
                ('price', models.IntegerField(default=0, help_text='BDT')),
                ('days', models.IntegerField(default=0, verbose_name='Validity Days')),
            ],
            options={
                'verbose_name_plural': 'V Vip Packages',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='VVipPackageOrderingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'V Vip Package Ordering Info',
            },
        ),
        migrations.CreateModel(
            name='PurchasedVVipPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_datetime', models.DateTimeField(auto_now_add=True)),
                ('expired_datetime', models.DateTimeField()),
                ('purchased_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vvip_purchased_from', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vvip_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.vvippackage')),
            ],
            options={
                'verbose_name_plural': 'Purchased V Vip Packages',
                'ordering': ['-purchased_datetime'],
            },
        ),
        migrations.CreateModel(
            name='PurchasedVipPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_datetime', models.DateTimeField(auto_now_add=True)),
                ('expired_datetime', models.DateTimeField()),
                ('purchased_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vip_purchased_from', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vip_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.vippackage')),
            ],
            options={
                'ordering': ['-purchased_datetime'],
            },
        ),
    ]
