# Generated by Django 4.2 on 2024-05-31 08:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_youtubevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedpackagetheme',
            name='custom_theme',
            field=models.ImageField(blank=None, default=django.utils.timezone.now, null=None, upload_to=products.models.package_theme_custom_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasedpackagetheme',
            name='package_theme',
            field=models.ForeignKey(blank=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='products.packagetheme'),
        ),
    ]
