# Generated by Django 4.2 on 2024-05-31 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_purchasedpackagetheme_custom_theme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedpackagetheme',
            old_name='custom_theme',
            new_name='custom_theme_image',
        ),
    ]
