# Generated by Django 4.2 on 2024-06-01 05:15

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_custom_theme_purchasedpackagetheme_custom_theme_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedpackagetheme',
            name='custom_theme_image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.package_theme_custom_path),
        ),
        migrations.AlterField(
            model_name='purchasedpackagetheme',
            name='package_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.packagetheme'),
        ),
    ]
